export const SET_DARK_MODE = 'SET_DARK_MODE';
export const SET_MOBILE_OPEN = 'SET_MOBILE_OPEN';

export const LOAD_WORLD_DATA = 'LOAD_WORLD_DATA';
export const SET_ACTIVE_WORLD_PROPS = 'SET_ACTIVE_WORLD_PROPS';
export const SET_SELECTED_WORLD_PROP = 'SET_SELECTED_WORLD_PROP'
export const SET_NUM_BARS = 'SET_NUM_BARS';
export const SET_WORLD_SEARCH = 'SET_WORLD_SEARCH';

export const LOAD_CURR_STATE_DATA = 'LOAD_CURR_STATE_DATA';
export const SET_ACTIVE_STATE_PROPS = 'SET_ACTIVE_STATE_PROPS';
export const SET_STATE_SEARCH = 'SET_STATE_SEARCH';

export const LOAD_HIST_STATE_DATA = 'LOAD_HIST_STATE_DATA';
export const SET_SELECTED_HIST_STATE = 'SET_SELECTED_HIST_STATE';
export const SET_SELECTED_HIST_PROP = 'SET_SELECTED_HIST_PROP';
